alias cal='cal -3'
alias cdwm='cd $HOME/.config/dwm && $EDITOR config.def.h'
alias ckitty='$EDITOR $HOME/.config/kitty/kitty.conf'
alias cnvim='$EDITOR $HOME/.config/nvim/init.vim'
alias cp='cp -iv'
alias devbox='ssh -Y mk@192.168.0.101'
alias df='df -h | grep -v snapd'
alias diff='diff --color=auto' 
alias f='fzf'
alias g='git'
alias gaa='git add .'
alias gc='git commit'
alias gcc='gcc -ansi -pedantic -std=c99 -Wall'
alias gcm='git commit -m'
alias gpl='git pull'
alias gps='git push'
alias gst='git status'
alias grep='grep --color=auto'
alias l='ls --color=auto'
alias la='ls --color=auto -lah'
alias ll='ls --color=auto -lh'
alias ls='ls --color=auto'
alias lf_='lf'
alias lf='lfrun'
alias matrix='unimatrix -n -s 96 -l o -a'
alias mkdir='mkdir -v'
alias py='python'
alias r='ranger'
alias ss='sudo systemctl'
# alias sv='sudo nvim'
alias svim='sudo nvim'
alias tree='tree --dirsfirst -C'
alias v='nvim'
alias vim='nvim'
alias xclip='xclip -selection clipboard'
